<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="Finbuckle.MultiTenant" />
    <PackageReference Include="Finbuckle.MultiTenant.EntityFrameworkCore" />
    <PackageReference Include="Scrutor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CyberErp.Srms.App\CyberErp.Srms.App.csproj" />
    <ProjectReference Include="..\CyberErp.Srms.Dom\CyberErp.Srms.Dom.csproj" />
  </ItemGroup>

</Project>
