import { Building2, ExternalLink, Globe2, MapPin, Pencil, UserRound } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { OrganizationRecord } from "@/services/api/multiTenantService";

export default function PlatformOrganizationSettingsView({ organization, onEdit }: { organization: OrganizationRecord; onEdit: () => void }) {
  const website = organization.website && !/^https?:\/\//i.test(organization.website) ? `https://${organization.website}` : organization.website;
  return <div className="overflow-hidden rounded-xl border border-border bg-card">
    <div className="flex flex-col gap-3 border-b px-4 py-3 sm:flex-row sm:items-center sm:justify-between">
      <div className="flex min-w-0 items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center overflow-hidden rounded-lg border border-primary/15 bg-primary/10 text-primary">{organization.logoUrl ? <img src={organization.logoUrl} alt="" className="h-full w-full object-contain p-1.5"/> : <Building2 className="h-5 w-5"/>}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate font-display text-sm font-semibold">{organization.displayName}</h3><Badge variant={organization.isActive ? "default" : "secondary"}>{organization.isActive ? "Active" : "Inactive"}</Badge></div><p className="mt-0.5 truncate text-xs text-muted-foreground">Organization identity, contacts, addresses, and operating defaults.</p></div></div>
      <Button size="sm" className="h-8 shrink-0 gap-1.5 self-start text-xs sm:self-auto" onClick={onEdit}><Pencil className="h-3.5 w-3.5"/>Edit Organization</Button>
    </div>
    <div className="bg-muted/10 p-4"><Tabs defaultValue="general"><TabsList className="max-w-full overflow-x-auto"><TabsTrigger value="general">General</TabsTrigger><TabsTrigger value="contact">Contact &amp; Address</TabsTrigger><TabsTrigger value="regional">Regional &amp; Fiscal</TabsTrigger></TabsList>
      <TabsContent value="general" className="grid gap-3 lg:grid-cols-2"><Section icon={Building2} title="Business Identity" description="Legal and registration information"><Row label="Organization code" value={organization.code}/><Row label="Legal name" value={organization.legalName}/><Row label="Organization type" value={organization.organizationType}/><Row label="Industry" value={organization.industry}/></Section><Section icon={Building2} title="Registration" description="Government and tax identifiers"><Row label="Registration number" value={organization.registrationNumber}/><Row label="Tax / VAT number" value={organization.taxNumber}/><Row label="TIN number" value={organization.tinNumber}/><Row label="Website" value={website ? <a href={website} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-primary hover:underline">Open website<ExternalLink className="h-3 w-3"/></a> : undefined}/></Section></TabsContent>
      <TabsContent value="contact" className="grid gap-3 lg:grid-cols-3"><Section icon={UserRound} title="Primary Contact" description="Main organization representative"><Row label="Name" value={organization.primaryContactName}/><Row label="Title" value={organization.primaryContactTitle}/><Row label="Email" value={organization.primaryContactEmail}/><Row label="Phone" value={organization.primaryContactPhone}/></Section><Section icon={UserRound} title="Organization Channels" description="General communication details"><Row label="Email" value={organization.email}/><Row label="Phone" value={organization.phone}/></Section><Section icon={MapPin} title="Address" description="Physical and postal location"><Row label="Physical address" value={organization.address}/><Row label="Postal address" value={organization.postalAddress}/><Row label="City / region" value={[organization.city, organization.region].filter(Boolean).join(", ")}/><Row label="Country" value={organization.country}/><Row label="Postal code" value={organization.postalCode}/></Section></TabsContent>
      <TabsContent value="regional" className="grid gap-3 lg:grid-cols-2"><Section icon={Globe2} title="Localization" description="Language, locale, and time settings"><Row label="Default language" value={organization.defaultLanguage}/><Row label="Locale" value={organization.locale}/><Row label="Timezone" value={organization.timezone}/><Row label="Date format" value={organization.dateFormat}/></Section><Section icon={Globe2} title="Financial Defaults" description="Currency and fiscal calendar"><Row label="Currency" value={organization.currency}/><Row label="Fiscal year starts" value={monthName(organization.fiscalYearStartMonth)}/><Row label="Data retention policy" value={organization.dataRetentionPolicy}/><Row label="Regulatory identifiers" value={organization.regulatoryIdentifiers}/></Section></TabsContent>
    </Tabs></div>
  </div>;
}

function Section({ icon: Icon, title, description, children }: { icon: typeof Building2; title: string; description: string; children: React.ReactNode }) { return <section className="space-y-3 rounded-xl border border-border bg-card p-4"><div className="flex items-center gap-2.5"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-primary/10"><Icon className="h-4 w-4 text-primary"/></span><div><h4 className="font-display text-sm font-semibold leading-tight">{title}</h4><p className="text-[11px] leading-tight text-muted-foreground">{description}</p></div></div><dl className="divide-y divide-border/70">{children}</dl></section>; }
function Row({ label, value }: { label: string; value: React.ReactNode }) { return <div className="flex items-start justify-between gap-4 py-2 first:pt-0 last:pb-0"><dt className="text-xs text-muted-foreground">{label}</dt><dd className="max-w-[65%] break-words text-right text-xs font-medium text-foreground">{value || "Not configured"}</dd></div>; }
function monthName(month: number) { return month < 1 || month > 12 ? String(month) : new Intl.DateTimeFormat(undefined, { month: "long" }).format(new Date(2024, month - 1, 1)); }
